version: '3.8'

services:
  finanzas-db:
    image: mariadb:11
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=finanzas_user
    - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./mariadb-data:/var/lib/mysql